version: '3.8'

services:
  
  postgres:
    image: "postgres:13"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: "messagesdb"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      
  web:
    image: messageexchangeservice.api
    build:
      context: .
      dockerfile: MessageExchangeService/src/MessageExchangeService.Api/Dockerfile
    ports:
      - "5252:5252"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=database;Port=5432;Database=messagesdb;Username=postgres;Password=1
    depends_on:
      - database  
  
volumes:
  postgres_data: