version: '3'

services:
  
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: "messagesdb"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  web:
    build:
      context: .
      dockerfile: MessageExchangeService/src/MessageExchangeService.Api/Dockerfile
    ports:
      - "5252:5252"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=messagesdb;Username=postgres;Password=1
      - ASPNETCORE_URLS=http://+:5252
    depends_on:
      - postgres

volumes:
  postgres_data:
