
# curl -X POST http://localhost:5252/api/messages -H "Content-Type: application/json" -d '{"Content":"Test message","SequenceNumber":1}'
POST http://localhost:5252/api/messages
Content-Type: application/json

{
  "Content": "Test message",
  "SequenceNumber": 1
}

###

# curl -X GET "http://localhost:5252/api/messages?start=2024-08-16T06:00:00Z&end=2024-08-16T07:00:00Z" -H "Content-Type: application/json"
GET http://localhost:5252/api/messages?start=2024-08-16T06:00:00Z&end=2024-08-16T07:00:00Z
Content-Type: application/json

###

